// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiLkb71aJXWPyiOWwWni0qrZHaa40nHcI',
    appId: '1:674155089068:web:db081932fdfb00aee1a309',
    messagingSenderId: '674155089068',
    projectId: 'regie-4c78a',
    authDomain: 'regie-4c78a.firebaseapp.com',
    storageBucket: 'regie-4c78a.firebasestorage.app',
    measurementId: 'G-0TT5RBPG69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMH7mXUgkfrlNRzKp8lxXc_cA66oy6D8',
    appId: '1:674155089068:android:af23dc49b021b2bae1a309',
    messagingSenderId: '674155089068',
    projectId: 'regie-4c78a',
    storageBucket: 'regie-4c78a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7yddTvM9C3bKoYWmDc29pDtaBBXfHkH8',
    appId: '1:674155089068:ios:9af4e5d9b94ab2c0e1a309',
    messagingSenderId: '674155089068',
    projectId: 'regie-4c78a',
    storageBucket: 'regie-4c78a.firebasestorage.app',
    iosClientId: '674155089068-prlt78qbg7gs3chl9bs3o8nnjjis6hr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.regieData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7yddTvM9C3bKoYWmDc29pDtaBBXfHkH8',
    appId: '1:674155089068:ios:9af4e5d9b94ab2c0e1a309',
    messagingSenderId: '674155089068',
    projectId: 'regie-4c78a',
    storageBucket: 'regie-4c78a.firebasestorage.app',
    iosClientId: '674155089068-prlt78qbg7gs3chl9bs3o8nnjjis6hr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.regieData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiLkb71aJXWPyiOWwWni0qrZHaa40nHcI',
    appId: '1:674155089068:web:d12c97eb9ec6e372e1a309',
    messagingSenderId: '674155089068',
    projectId: 'regie-4c78a',
    authDomain: 'regie-4c78a.firebaseapp.com',
    storageBucket: 'regie-4c78a.firebasestorage.app',
    measurementId: 'G-KPPXKT21BE',
  );
}
